feat: add default logger
keytiles/lib-logging-golang pull request #1
Opened 2023-08-18 21:08 UTC by vikkymanit

Adding a default logger and fixing panic when trying to get a logger without initialisation.

2023-08-22 12:13 UTC, AttilaW-Keytiles commented
The changes now look good!
but...

It deviates from the main branch - e.g. CHANGELOG is completely invalid now

I would recommend to fork a new branch out from main now, apply changes there, and open a new PR
we could take that
And then we could close these PRs

2023-08-22 12:16 UTC, AttilaW-Keytiles requested changes
all good - but see my main comment in conversation

2023-08-22 12:16 UTC, AttilaW-Keytiles commented on ktlogging.go
> +	if loggers == nil {
looks good

2023-08-22 12:16 UTC, AttilaW-Keytiles commented on CHANGELOG.md
> +## release 1.0.1
this is deviating a lot from current main branch so see my in general comment!

2023-08-22 12:16 UTC, AttilaW-Keytiles commented on ktlogging.go
> +func getDefaultLoggerConfig() ConfigModel {
also looks good

2023-08-24 21:59 UTC, vikkymanit commented
I have merged the latest from main onto this branch. So we should be fine now.

2023-08-24 22:00 UTC, vikkymanit commented on CHANGELOG.md
> +## release 1.0.1
I have merged the latest from main onto this branch. So we should be fine now.

2023-08-25 17:03 UTC, AttilaW-Keytiles approved these changes
looks good - lets merge and move on

2023-08-26 07:34 UTC, merged